name: ONE Record Project Card Template
description: File a Project Card for the ONE Record standard.
title: "[Project Card]: "
labels: ["Project Card", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a test report for the ONE Record standard!

  - type: input
    id: projectName
    attributes:
      label: Project Name
      description: Enter the name of the project.
      placeholder: Project Name

  - type: textarea
    id: projectObjective
    attributes:
      label: Project Objective
      description: Describe the objective of the project.
      placeholder: Project Objective

  - type: textarea
    id: useCaseObjective
    attributes:
      label: Use Case Objective
      description: Describe the objective of the use case.
      placeholder: Use Case Objective

  - type: dropdown
    id: projectPhase
    attributes:
      label: Project Phase
      description: Select the phase of the project.
      options:
        - Exploration/ PoC
        - IATA Unit Test
        - IATA Integration Test
        - E2E Pilot Project
        - Live Production
      
  - type: input
    id: startDate
    attributes:
      label: Start Date
      description: Select the start date of the project.
      placeholder: Select Date

  - type: input
    id: endDate
    attributes:
      label: End Date
      description: Select the end date of the project.
      placeholder: Select Date

  - type: input
    id: accountablePerson
    attributes:
      label: Accountable Person
      description: Enter the name of the accountable person.
      placeholder: Accountable Person

  - type: textarea
    id: companyInformation
    attributes:
      label: Company Information
      description: Provide details about the company associated with the project. List all "Company Name / Company Representative".
      placeholder: Company Information

  - type: input
    id: standardVersion
    attributes:
      label: Standard Version
      description: Enter the version of the ONE Record standard being used.
      placeholder: Standard Version

  - type: checkboxes
    id: oneRecordDataModel
    attributes:
      label: ONE Record Data Model
      description: Select the elements of the ONE Record Data Model.
      options:
        - label: Airline Core Ontology
        - label: Shipper's Letter of Instruction
        - label: Cargo Distribution
        - label: CO2 Emission
        - label: Billing & Settlement
        - label: ULD Tracking
        - label: Interactive Cargo
        - label: Dangerous Goods
        - label: Pharmaceutical
        - label: Advanced Cargo Information
        - label: Ground Handling

  - type: checkboxes
    id: oneRecordAPIFeatures
    attributes:
      label: ONE Record API Features
      description: Select the features of the ONE Record API.
      options:
        - label: PUB/SUB
        - label: LO update
        - label: Access delegation
        - label: Security
        - label: Event
        - label: Audit train / Versioning
        - label: Access Control
        - label: Cascading status update - Pub/Sub in multi chain
        - label: Data integrity / non repudiation with RDF
        - label: SHACL shapes
        - label: IoT updates
        - label: Rich data

  - type: textarea
    id: lessonsLearned
    attributes:
      label: Lessons Learned
      description: Provide any lessons learned, challenges, outcomes, or questions.
      placeholder: Lessons Learned (challenges, outcome, questions)
